INCOME_STATEMENT:
  GROSS_REVENUE: 10
  DEDUCTIONS: 11
  NET_REVENUE: 20
  COST_OF_GOODS_SOLD: 21
  GROSS_PROFIT: 30
  FINANCIAL_INCOME: 31
  FINANCIAL_EXPENSES: 32
  INTEREST_EXPENSES: 33
  SHARE_OF_NET_PROFIT_FROM_ASSOCIATES_AND_JOINT_VENTURES: 34
  SELLING_EXPENSES: 35
  GENERAL_AND_ADMINISTRATIVE_EXPENSES: 36
  OPERATING_PROFIT: 40
  OTHER_INCOME: 41
  OTHER_EXPENSES: 42
  OTHER_PROFITS: 50
  NET_PROFIT_BEFORE_TAX: 60
  CURRENT_INCOME_TAX_EXPENSE: 61
  DEFERRED_INCOME_TAX_EXPENSE: 62
  INCOME_TAX_EXPENSE: 63
  NET_PROFIT_AFTER_TAX: 70
  NET_PROFIT_AFTER_TAX_ATTRIBUTE_TO_NON_CONTROLLING_INTERESTS: 71
  NET_PROFIT_AFTER_TAX_ATTRIBUTE_TO_MAJORITY_SHAREHOLDERS: 72
  SHARES_OUTSTANDING_: 
  BASIC_EPS: 80
  DILUTED_EPS: 81

BALANCE_SHEET: 
  CURRENT_ASSETS: 1000
  CASH_AND_CASH_EQUIVALENTS: 1100
  CASH: 1110
  CASH_EQUIVALENTS: 1120
  SHORT_TERM_INVESTMENTS: 1200
  HELD_FOR_TRADING_SECURITIES: 1210
  PROVISION_FOR_DEVALUATION_OF_TRADING_SECURITIES: 1220
  HELD_TO_MATURITY_SHORT_TERM_INVESTMENTS: 1230
  CURRENT_ACCOUNTS_RECEIVABLE: 1300
  SHORT_TERM_TRADE_RECEIVABLES: 1310
  SHORT_TERM_ADVANCES_TO_SUPPLIERS: 1320
  SHORT_TERM_INTER_COMPANY_RECEIVABLES: 1330
  PROGRESS_BILLINGS_ON_CONSTRUCTION_CONTRACTS: 1340
  SHORT_TERM_LOANS_RECEIVABLES_: 1350
  OTHER_SHORT_TERM_RECEIVABLES: 1360
  ALLOWANCE_FOR_SHORT_TERM_DOUBTFUL_ACCOUNTS: 1370
  INVENTORY: 1400
  INVENTORIES: 1410
  ALLOWANCE_FOR_OBSOLETE_INVENTORIES: 1420
  OTHER_CURRENT_ASSETS: 1500
  SHORT_TERM_PREPAID_EXPENSE: 1510
  DEDUCTIBLE_VAT: 1520
  TAXES_AND_RECEIVABLES_FROM_STATE_BUDGET: 1530
  GOVERNMENT_BONDS_PURCHASED_FOR_RESALE: 1540
  OTHER_CURRENT_ASSETS: 1550
  NON_CURRENT_ASSETS: 2000
  LONG_TERM_RECEIVABLES: 2100
  LONG_TERM_TRADE_RECEIVABLES: 2110
  WORKING_CAPITAL_IN_SUBSIDIARIES: 2120
  INTERNAL_LONG_TERM_RECEIVABLES: 2130
  LONG_TERM_LOANS_RECEIVABLES_: 2140
  OTHER_LONG_TERM_RECEIVABLES: 2150
  ALLOWANCE_FOR_LONG_TERM_DOUBTFUL_ACCOUNTS: 2160
  FIXED_ASSETS: 2200
  TANGIBLE_FIXED_ASSET: 2210
  TANGIBLE_FIXED_ASSET_COST: 2211
  TANGIBLE_FIXED_ASSET_ACCUMULATED_DEPRECIATION: 2212
  FINANCE_LEASE_FIXED_ASSET: 2220
  FINANCE_LEASE_FIXED_ASSET_COST: 2221
  FINANCE_LEASE_FIXED_ASSET_ACCUMULATED_DEPRECIATION: 2222
  INTANGIBLE_FIXED_ASSET: 2230
  INTANGIBLE_FIXED_ASSET_COST: 2231
  INTANGIBLE_FIXED_ASSET_ACCUMULATED_DEPRECIATION: 2232
  INVESTMENT_PROPERTY: 2300
  INVESTMENT_PROPERTIES_COST: 2310
  INVESTMENT_PROPERTIES_ACCUMULATED_DEPRECIATION: 2320
  LONG_TERM_ASSETS_IN_PROGRESS: 2400
  LONG_TERM_WORK_IN_PROGRESS: 2410
  CONSTRUCTION_IN_PROGRESS: 2420
  LONG_TERM_INVESTMENTS: 2500
  LONG_TERM_INVESTMENT_IN_SUBSIDIARIES: 2510
  LONG_TERM_INVESTMENT_IN_ASSOCIATES_AND_JOINT_VENTURES: 2520
  LONG_TERM_INVESTMENT_IN_OTHER_ENTITIES: 2530
  PROVISION_FOR_LONG_TERM_INVESTMENTS: 2540
  HELD_TO_MATURITY_LONG_TERM_INVESTMENTS: 2550
  OTHER_LONG_TERM_ASSETS: 2600
  LONG_TERM_PREPAID_EXPENSE: 2610
  DEFERRED_INCOME_TAX_ASSETS: 2620
  OTHER_LONG_TERM_ASSETS: 2630
  GOODWILL: 2700
  TOTAL_ASSETS: 2800

CAPITAL_RESOURCES: 
  LIABILITIES: 3000
  CURRENT_LIABILITIES: 3100
  SHORT_TERM_BORROWINGS_AND_FINANCE_LEASE_LIABILITIES: 3110
  CURRENT_PORTION_OF_LONG_TERM_DEBT: 3120
  SHORT_TERM_TRADE_PAYABLES: 3130
  SHORT_TERM_ADVANCES_FROM_CUSTOMERS: 3140
  TAXES_AND_PAYABLES_TO_STATE_BUDGET: 3150
  PAYABLES_TO_EMPLOYEES: 3160
  SHORT_TERM_ACCRUED_EXPENSE: 3170
  SHORT_TERM_INTERCOMPANY_PAYABLES: 3180
  PROGRESS_PAYMENTS_UNDER_CONSTRUCTION_CONTRACTS: 3190
  SHORT_TERM_DEFERRED_REVENUE: 3200
  OTHER_SHORT_TERM_PAYABLES: 3210
  SHORT_TERM_PROVISIONS: 3220
  BONUS_AND_WELFARE_FUND: 3230
  PRICE_STABILIZATION_FUND: 3240
  GOVERNMENT_BONDS_PURCHASED_FOR_RESALE: 3250
  NON_CURRENT_LIABILITIES: 3300
  LONG_TERM_TRADE_CREDITORS: 3310
  LONG_TERM_ACCRUED_EXPENSE: 3320
  INTERCOMPANY_PAYABLES_ON_WORKING_CAPITAL: 3330
  LONG_TERM_INTRACOMPANY_PAYABLES: 3340
  OTHER_LONG_TERM_PAYABLES: 3350
  LONG_TERM_BORROWINGS_AND_FINANCE_LEASE_LIABILITIES: 3360
  CONVERTIBLE_BONDS: 3370
  DEFERRED_INCOME_TAX_PAYABLES: 3380
  SEVERANCE_ALLOWANCES: 3390
  LONG_TERM_PROVISIONS: 3400
  LONG_TERM_DEFERRED_REVENUE: 3410
  SCIENCE_AND_TECHNOLOGY_DEVELOPMENT_FUND: 3420
  OWNERS_EQUITY: 4000
  SHAREHOLDERS_EQUITY: 4100
  OWNERS_CAPITAL: 4110
  CAPITAL_SURPLUS: 4120
  CONVERTIBLE_BOND_OPTION: 4130
  OTHER_CAPITAL: 4140
  TREASURY_SHARES: 4150
  DIFFERENCES_UPON_ASSET_REVALUATION: 4160
  EXCHANGE_RATE_DIFFERENCES: 4170
  INVESTMENT_AND_DEVELOPMENT_FUNDS: 4180
  RESERVE_FUND: 4190
  OTHER_EQUITY_FUND: 4200
  RETAINED_EARNINGS: 4210
  RETAINED_EARNINGS_ACCUMULATED_TO_THE_PRIOR_PERIOD_END: 4211
  RETAINED_EARNINGS_THIS_PERIOD: 4212
  CAPITAL_EXPENDITURE_FUND: 4220
  ENTERPRISE_ARRANGEMENT_AND_DEVELOPMENT_SUPPORT_FUND: 4230
  NON_CONTROLLING_INTERESTS: 4240
  OTHER_RESOURCES_AND_FUNDS: 4300
  FUNDING_RESOURCES: 4310
  FIXED_ASSETS_ACQUISITION: 4320
  PROVIDENT_FUND: 4330
  TOTAL_LIABILITIES_AND_EQUITY: 4400


CASHFLOW_STATEMENT: 

  NET_PROFIT_BEFORE_TAX: 
  ADJUSTMENTS: 110
  DEPRECIATION_AND_AMORTISATION: 111
  PROVISIONS: 112
  NET_PROFIT_FROM_INVESTMENT_IN_JOINT_VENTURE: 113
  WRITE_OFF_FIXED_ASSETS: 114
  UNREALISED_FOREIGN_EXCHANGE_RATE_DIFFERENCES: 115
  GAIN_FROM_DISPOSAL_OF_FIXED_ASSETS: 116
  PROFIT_FROM_INVESTING_ACTIVITIES: 117
  CREDIT_INTEREST: 118
  INTEREST_INCOME: 119
  INTEREST_EXPENSE: 120
  PAYMENTS_DIRECT_FROM_PROFIT: 121
  OPERATING_PROFIT_BEFORE_WORKING_CAPITAL_CHANGES: 130
  CHANGES_IN_RECEIVABLES: 131
  CHANGES_IN_INVENTORIES: 132
  CHANGES_IN_PAYABLES: 133
  CHANGES_IN_PREPAID_EXPENSE: 134
  CHANGES_IN_CURRENT_ASSETS: 135
  INTEREST_PAID: 136
  INCOME_TAX_PAID: 137
  OTHER_RECEIPTS_FROM_OPERATING_ACTIVITIES: 138
  OTHER_PAYMENTS_FROM_OPERATING_ACTIVITIES: 139
  NET_CASH_FLOW_FROM_OPERATING_ACTIVITIES: 140

  PURCHASES_OF_FIXED_ASSETS: 201
  PROCEEDS_FROM_DISPOSALS_OF_FIXED_ASSETS: 202
  PURCHASES_OF_DEBT_INSTRUMENTS_OF_OTHER_ENTITIES: 203
  PROCEEDS_FROM_SALES_OF_DEBT_INSTRUMENTS_OF_OTHER_ENTITIES: 204
  INVESTMENT_IN_ASSOCIATES_AND_JOINT_VENTURES: 205
  SHORT_TERM_INVESTMENT_EXPENDITURES: 206
  INVESTMENT_IN_OTHER_ENTITIES: 207
  CAPITAL_WITHDRAWAL_IN_OTHER_ENTITIES: 208
  CREDIT_INTEREST_RECEIVABLE: 209
  DIVIDENDS_AND_INTEREST_RECEIVED: 210
  MINORITY_ACQUISITIONS: 211
  NET_CASH_FLOW_FROM_INVESTING_ACTIVITIES: 220

  PROCEEDS_FROM_SHARE_ISSUE_AND_CAPITAL_CONTRIBUTION: 301
  CAPITAL_REDEMPTION_AND_REPURCHASE_OF_ISSUED_SHARES: 302
  PROCEEDS_FROM_BORROWINGS: 303
  PRINCIPAL_PAYMENT: 304
  FINANCIAL_LEASE_PAYMENT: 305
  OTHER_PAYMENTS_FROM_FINANCING_ACTIVITIES: 306
  EQUITISATION_PAYMENT: 307
  DIVIDENDS_PAID: 308
  MINORITY_EQUITY_IN_JOINT_VENTURE: 309
  SOCIAL_WELFARE_EXPENSES: 310
  NET_CASH_FLOW_FROM_FINANCING_ACTIVITIES: 320
  NET_CASH_FLOW_OF_PERIOD: 400
  CASH_AND_CASH_EQUIVALENTS_AT_BEGINNING_OF_PERIOD: 410
  EFFECT_OF_EXCHANGE_RATE_FLUCTUATION: 411
  CASH_AND_CASH_EQUIVALENTS_AT_PERIOD_END: 420

  SHARES_OUTSTANDING: 9000
  EPS: 9010
  DIVIDEND_IN_CASH_3Y_AVERAGE: 9020